services:
  trello-clone:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src/app
    command: sh -c "npm start"
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    tty: true
